"""Findings drawn from the Received chain, timestamps, and message identifiers."""

from __future__ import annotations

from mailtrace_core.case.settings import Settings
from mailtrace_core.models import Confidence, Evidence, Finding, ParsedEmail, Severity
from mailtrace_core.parsing.urls import registrable_domain


def run(pe: ParsedEmail, settings: Settings) -> list[Finding]:
    out: list[Finding] = []
    for hop in pe.hops:
        for anomaly in hop.anomalies:
            if "out of order" in anomaly:
                out.append(
                    Finding(
                        rule_id="HA-001",
                        title=f"Hop {hop.index} timestamp is out of order",
                        confidence=Confidence.CONFIRMED,
                        severity=Severity.MEDIUM,
                        category="headers",
                        explanation=anomaly + ". Either a server clock is badly wrong or the older "
                        "Received header was fabricated by the sender.",
                        evidence=[Evidence(f"hop:{hop.index}", hop.raw)],
                    )
                )
            elif "implausibly long delay" in anomaly:
                out.append(
                    Finding(
                        rule_id="HA-002",
                        title=f"Hop {hop.index} shows an implausible delay",
                        confidence=Confidence.CONFIRMED,
                        severity=Severity.LOW,
                        category="headers",
                        explanation=anomaly + ". Queued mail or a forged earlier hop.",
                        evidence=[Evidence(f"hop:{hop.index}", hop.raw)],
                    )
                )
            elif "neither 'from' nor 'by'" in anomaly or "unparseable timestamp" in anomaly:
                out.append(
                    Finding(
                        rule_id="HA-006",
                        title=f"Hop {hop.index} is malformed",
                        confidence=Confidence.CONFIRMED,
                        severity=Severity.LOW,
                        category="headers",
                        explanation=anomaly,
                        evidence=[Evidence(f"hop:{hop.index}", hop.raw)],
                    )
                )
    for w in pe.warnings:
        if w.startswith("Date header"):
            out.append(
                Finding(
                    rule_id="HA-003",
                    title="Date header inconsistent with transit timestamps",
                    confidence=Confidence.CONFIRMED,
                    severity=Severity.LOW,
                    category="headers",
                    explanation=w,
                    evidence=[Evidence("header:Date", pe.header("Date") or "")],
                )
            )
    if pe.hops and not any(h.trusted for h in pe.hops):
        out.append(
            Finding(
                rule_id="HA-004",
                title="No trusted recipient-side hop could be identified",
                confidence=Confidence.UNVERIFIED,
                severity=Severity.INFO,
                category="headers",
                explanation="None of the Received headers could be tied to the recipient's mail "
                "infrastructure, so every hop and the originating IP are unverified. Configure "
                "the recipient's domain in Settings to establish a trust boundary.",
                evidence=[Evidence("hops", f"{len(pe.hops)} hop(s)")],
            )
        )
    mid = pe.message_id
    if not mid:
        out.append(
            Finding(
                rule_id="HA-005",
                title="No Message-ID header",
                confidence=Confidence.CONFIRMED,
                severity=Severity.LOW,
                category="headers",
                explanation="Nearly all real mail software adds a Message-ID; its absence suggests "
                "a script or a stripped message.",
            )
        )
    elif pe.from_ and pe.from_.domain and "@" in mid:
        mid_dom = mid.strip("<>").rpartition("@")[2].lower()
        if mid_dom and registrable_domain(mid_dom) != registrable_domain(pe.from_.domain):
            out.append(
                Finding(
                    rule_id="HA-005",
                    title="Message-ID domain differs from From domain",
                    confidence=Confidence.CONFIRMED,
                    severity=Severity.INFO,
                    category="headers",
                    explanation="The Message-ID was generated by a system in a different domain. "
                    "Very common with outsourced mail providers; occasionally a sign of "
                    "third-party sending tools.",
                    evidence=[
                        Evidence("header:Message-ID", mid),
                        Evidence("header:From", pe.from_.address),
                    ],
                )
            )
    return out
